import type { Metadata } from "next";
import { Geist, Geist_Mono, Kaushan_Script } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const kaushanScript = Kaushan_Script({
  subsets: ["latin"],
  weight: "400",
  variable: '--font-kuaschan-script'
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${kaushanScript.variable} antialiased bg-black`}
      >
        <Navbar/>
        <main className="max-w-[2200px] mx-auto">
          {children}
        </main>
      </body>
    </html>
  );
}
